#pragma once
#include <avr/pgmspace.h>


// COMMANDS
REG_STR(		COMM_AT,					"AT" );
REG_STR(		COMM_CHECK_NETWORK,			"AT+CREG?");
REG_STR(		COMM_ECHO_OFF,				"ATE0");
REG_STR(		COMM_RESPONSE_MODE,			"ATV1");
REG_STR(		COMM_GSM_ACTIVITY,			"AT+CPAS");
REG_STR(		COMM_HANGUP,				"ATH");
REG_STR(		COMM_READ_SMS,				"AT+CMGR=");
REG_STR(		COMM_DELETE_SMS,			"AT+CMGD=1,4");
REG_STR(		COMM_SEND_SMS,				"AT+CMGS=");
REG_STR(		COMM_SET_CLOCK,				"AT+CCLK=");
REG_STR(		COMM_GET_CLOCK,				"AT+CCLK?");

// RESPONSES
REG_STR(		RESP_POWER_DOWN,			"NORMAL POWER DOWN" );
REG_STR(		RESP_CALL_READY,			"Call Ready" );
REG_STR(		RESP_OK,					"OK" );
REG_STR(		RESP_CHECK_NETWORK,			"+CREG: 0,1" );
REG_STR(		RESP_GSM_ACTIVITY,			"+CPAS: " );
REG_STR(		RESP_NEW_SMS,				"+CMTI: \"SM\",");
REG_STR(		RESP_RING,					"RING");
REG_STR(		RESP_CLIP,					"+CLIP: ");
REG_STR(		RESP_ERROR,					"ERROR");
REG_STR(		RESP_READ_SMS,				"+CMGR:");
REG_STR(		RESP_UNREAD_SMS,			"REC UNREAD");
REG_STR(		RESP_READY_FOR_SMS,			">");
REG_STR(		RESP_SEND_SMS,				"+CMGS: ");
REG_STR(		RESP_GET_CLOCK,				"+CCLK:");
